In [1]:
import cv2
import tensorflow as tf

CATEGORIES = ["Cat", "Dog"]
# Dog = 1, Cat = 0

In [2]:
def prepare(filepath):
    IMG_SIZE = 100
    img_array = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
    img_array = img_array / 255.0
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 1)

In [3]:
model = tf.keras.models.load_model("Final-3conv-128nodes-0dense")

In [4]:
prediction1 = model.predict([prepare('cat-train.jpg')])

In [5]:
prediction1

array([[0.]], dtype=float32)

In [6]:
prediction2 = model.predict([prepare('akira.jpeg')])
prediction2

array([[0.9999969]], dtype=float32)

In [7]:
# Kit harrington
prediction2 = model.predict([prepare('down1.jif')])
prediction2

array([[0.9999893]], dtype=float32)

In [8]:
prediction3 = model.predict([prepare('milind.jpeg')])
prediction3


array([[0.99999964]], dtype=float32)

In [12]:
prediction3.reshape(1)[0]

0.99999964